### ISSUE TITLE
Crash when using Zoom effect

### ISSUE THREAD

**Issue by krisives** [zzag/kwin-effects-yet-another-magic-lamp#16]
I reported a crash to KDE and they mentioned it might actually be happening within this YAML effect:

https://bugs.kde.org/show_bug.cgi?id=412875

Here is the stack trace:

```

-- Backtrace:
Application: KWin (kwin_x11), signal: Segmentation fault
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Current thread is 1 (Thread 0x7ff473293d00 (LWP 1227))]

Thread 7 (Thread 0x7ff43ac4e700 (LWP 2956)):
#0  0x00007ff46bb499f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55908e0dbf10) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  0x00007ff46bb499f3 in __pthread_cond_wait_common (abstime=0x0, mutex=0x55908e0dbec0, cond=0x55908e0dbee8) at pthread_cond_wait.c:502
#2  0x00007ff46bb499f3 in __pthread_cond_wait (cond=0x55908e0dbee8, mutex=0x55908e0dbec0) at pthread_cond_wait.c:655
#3  0x00007ff46fefcb0b in QWaitCondition::wait(QMutex*, QDeadlineTimer) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ff46fefce19 in QWaitCondition::wait(QMutex*, unsigned long) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ff46acd3ec8 in  () at /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#6  0x00007ff46acd42fa in  () at /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#7  0x00007ff46fef5b72 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ff46bb436db in start_thread (arg=0x7ff43ac4e700) at pthread_create.c:463
#9  0x00007ff472bf988f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7ff43a44d700 (LWP 1362)):
#0  0x00007ff46bb499f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7ff46f101fb8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  0x00007ff46bb499f3 in __pthread_cond_wait_common (abstime=0x0, mutex=0x7ff46f101f68, cond=0x7ff46f101f90) at pthread_cond_wait.c:502
#2  0x00007ff46bb499f3 in __pthread_cond_wait (cond=0x7ff46f101f90, mutex=0x7ff46f101f68) at pthread_cond_wait.c:655
#3  0x00007ff46ee0c874 in  () at /usr/lib/x86_64-linux-gnu/libQt5Script.so.5
#4  0x00007ff46ee0c8b9 in  () at /usr/lib/x86_64-linux-gnu/libQt5Script.so.5
#5  0x00007ff46bb436db in start_thread (arg=0x7ff43a44d700) at pthread_create.c:463
#6  0x00007ff472bf988f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7ff4408e4700 (LWP 1355)):
#0  0x00007ff46bb499f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55908da56d6c) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  0x00007ff46bb499f3 in __pthread_cond_wait_common (abstime=0x0, mutex=0x55908da56d18, cond=0x55908da56d40) at pthread_cond_wait.c:502
#2  0x00007ff46bb499f3 in __pthread_cond_wait (cond=0x55908da56d40, mutex=0x55908da56d18) at pthread_cond_wait.c:655
#3  0x00007ff4414b62cb in  () at /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#4  0x00007ff4414b5ff7 in  () at /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#5  0x00007ff46bb436db in start_thread (arg=0x7ff4408e4700) at pthread_create.c:463
#6  0x00007ff472bf988f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7ff4510f1700 (LWP 1340)):
#0  0x00007ff472beccf6 in __GI_ppoll (fds=0x7ff448000d28, nfds=1, timeout=<optimized out>, sigmask=0x0) at ../sysdeps/unix/sysv/linux/ppoll.c:39
#1  0x00007ff4701346e1 in qt_safe_poll(pollfd*, unsigned long, timespec const*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007ff470135e78 in QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007ff4700d8eaa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ff46fef43ca in QThread::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ff46a54ecb5 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#6  0x00007ff46fef5b72 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007ff46bb436db in start_thread (arg=0x7ff4510f1700) at pthread_create.c:463
#8  0x00007ff472bf988f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7ff453bf0700 (LWP 1274)):
#0  0x00007ff472beccf6 in __GI_ppoll (fds=0x7ff44c00b8d8, nfds=1, timeout=<optimized out>, sigmask=0x0) at ../sysdeps/unix/sysv/linux/ppoll.c:39
#1  0x00007ff4701346e1 in qt_safe_poll(pollfd*, unsigned long, timespec const*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007ff470135e78 in QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007ff4700d8eaa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ff46fef43ca in QThread::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ff4693c10e5 in  () at /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#6  0x00007ff46fef5b72 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007ff46bb436db in start_thread (arg=0x7ff453bf0700) at pthread_create.c:463
#8  0x00007ff472bf988f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7ff45a198700 (LWP 1244)):
#0  0x00007ff472becbf9 in __GI___poll (fds=0x7ff45a197c28, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ff46fc2e747 in  () at /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007ff46fc3036a in xcb_wait_for_event () at /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007ff45b4d1f00 in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007ff46fef5b72 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ff46bb436db in start_thread (arg=0x7ff45a198700) at pthread_create.c:463
#6  0x00007ff472bf988f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7ff473293d00 (LWP 1227)):
[KCrash Handler]
#6  0x00007ff46b4d4a50 in KWin::GLTexture::matrix(KWin::TextureCoordinateType) const () at /usr/lib/x86_64-linux-gnu/libkwinglutils.so.12
#7  0x00007ff439528228 in WindowMeshRenderer::render(KWin::EffectWindow*, QVector<WindowQuad> const&, KWin::GLTexture*, QRegion const&) const () at /usr/lib/x86_64-linux-gnu/qt5/plugins/kwin/effects/plugins/libkwin4_effect_yetanothermagiclamp.so
#8  0x00007ff439529246 in YetAnotherMagicLampEffect::drawWindow(KWin::EffectWindow*, int, QRegion, KWin::WindowPaintData&) () at /usr/lib/x86_64-linux-gnu/qt5/plugins/kwin/effects/plugins/libkwin4_effect_yetanothermagiclamp.so
#9  0x00007ff472741a2e in KWin::EffectsHandlerImpl::drawWindow(KWin::EffectWindow*, int, QRegion, KWin::WindowPaintData&) () at /usr/lib/x86_64-linux-gnu/libkwin.so.5
#10 0x00007ff46f678410 in KWin::Effect::drawWindow(KWin::EffectWindow*, int, QRegion, KWin::WindowPaintData&) () at /usr/lib/x86_64-linux-gnu/libkwineffects.so.12
#11 0x00007ff472741a2e in KWin::EffectsHandlerImpl::drawWindow(KWin::EffectWindow*, int, QRegion, KWin::WindowPaintData&) () at /usr/lib/x86_64-linux-gnu/libkwin.so.5
#12 0x00007ff47272ff20 in KWin::Scene::finalPaintWindow(KWin::EffectWindowImpl*, int, QRegion, KWin::WindowPaintData&) () at /usr/lib/x86_64-linux-gnu/libkwin.so.5
#13 0x00007ff4727418bd in KWin::EffectsHandlerImpl::paintWindow(KWin::EffectWindow*, int, QRegion, KWin::WindowPaintData&) () at /usr/lib/x86_64-linux-gnu/libkwin.so.5
#14 0x00007ff46f6782a0 in KWin::Effect::paintWindow(KWin::EffectWindow*, int, QRegion, KWin::WindowPaintData&) () at /usr/lib/x86_64-linux-gnu/libkwineffects.so.12
#15 0x00007ff47274185e in KWin::EffectsHandlerImpl::paintWindow(KWin::EffectWindow*, int, QRegion, KWin::WindowPaintData&) () at /usr/lib/x86_64-linux-gnu/libkwin.so.5
#16 0x00007ff46f6782a0 in KWin::Effect::paintWindow(KWin::EffectWindow*, int, QRegion, KWin::WindowPaintData&) () at /usr/lib/x86_64-linux-gnu/libkwineffects.so.12
#17 0x00007ff47274185e in KWin::EffectsHandlerImpl::paintWindow(KWin::EffectWindow*, int, QRegion, KWin::WindowPaintData&) () at /usr/lib/x86_64-linux-gnu/libkwin.so.5
#18 0x00007ff46f681627 in KWin::AnimationEffect::paintWindow(KWin::EffectWindow*, int, QRegion, KWin::WindowPaintData&) () at /usr/lib/x86_64-linux-gnu/libkwineffects.so.12
#19 0x00007ff47274185e in KWin::EffectsHandlerImpl::paintWindow(KWin::EffectWindow*, int, QRegion, KWin::WindowPaintData&) () at /usr/lib/x86_64-linux-gnu/libkwin.so.5
#20 0x00007ff4727363b5 in KWin::Scene::paintWindow(KWin::Scene::Window*, int, QRegion, KWin::WindowQuadList) () at /usr/lib/x86_64-linux-gnu/libkwin.so.5
#21 0x00007ff472733b75 in KWin::Scene::paintGenericScreen(int, KWin::ScreenPaintData) () at /usr/lib/x86_64-linux-gnu/libkwin.so.5
#22 0x00007ff4500a3bf2 in  () at /usr/lib/x86_64-linux-gnu/qt5/plugins/org.kde.kwin.scenes/KWinSceneOpenGL.so
#23 0x00007ff4727358e0 in KWin::Scene::finalPaintScreen(int, QRegion, KWin::ScreenPaintData&) () at /usr/lib/x86_64-linux-gnu/libkwin.so.5
#24 0x00007ff472741615 in KWin::EffectsHandlerImpl::paintScreen(int, QRegion, KWin::ScreenPaintData&) () at /usr/lib/x86_64-linux-gnu/libkwin.so.5
#25 0x00007ff46f6781f1 in KWin::Effect::paintScreen(int, QRegion, KWin::ScreenPaintData&) () at /usr/lib/x86_64-linux-gnu/libkwineffects.so.12
#26 0x00007ff4727415bd in KWin::EffectsHandlerImpl::paintScreen(int, QRegion, KWin::ScreenPaintData&) () at /usr/lib/x86_64-linux-gnu/libkwin.so.5
#27 0x00007ff46f6781f1 in KWin::Effect::paintScreen(int, QRegion, KWin::ScreenPaintData&) () at /usr/lib/x86_64-linux-gnu/libkwineffects.so.12
#28 0x00007ff4727415bd in KWin::EffectsHandlerImpl::paintScreen(int, QRegion, KWin::ScreenPaintData&) () at /usr/lib/x86_64-linux-gnu/libkwin.so.5
#29 0x00007ff46f6781f1 in KWin::Effect::paintScreen(int, QRegion, KWin::ScreenPaintData&) () at /usr/lib/x86_64-linux-gnu/libkwineffects.so.12
#30 0x00007ff4727415bd in KWin::EffectsHandlerImpl::paintScreen(int, QRegion, KWin::ScreenPaintData&) () at /usr/lib/x86_64-linux-gnu/libkwin.so.5
#31 0x00007ff47273558e in KWin::Scene::paintScreen(int*, QRegion const&, QRegion const&, QRegion*, QRegion*, QMatrix4x4 const&, QRect const&) () at /usr/lib/x86_64-linux-gnu/libkwin.so.5
#32 0x00007ff45009fd11 in KWin::SceneOpenGL::paint(QRegion, QList<KWin::Toplevel*>) () at /usr/lib/x86_64-linux-gnu/qt5/plugins/org.kde.kwin.scenes/KWinSceneOpenGL.so
#33 0x00007ff472727bd2 in KWin::Compositor::performCompositing() () at /usr/lib/x86_64-linux-gnu/libkwin.so.5
#34 0x00007ff47010c22b in QObject::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#35 0x00007ff470edfeac in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#36 0x00007ff470ee74b0 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#37 0x00007ff4700dad48 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#38 0x00007ff470137e49 in QTimerInfoList::activateTimers() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#39 0x00007ff47013617a in QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#40 0x00007ff45b4d324e in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#41 0x00007ff4700d8eaa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#42 0x00007ff4700e2220 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#43 0x00007ff472ed1f88 in kdemain () at /usr/lib/x86_64-linux-gnu/libkdeinit5_kwin_x11.so
#44 0x00007ff472af9b97 in __libc_start_main (main=0x55908be5b720, argc=3, argv=0x7ffeda048268, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffeda048258) at ../csu/libc-start.c:310
#45 0x000055908be5b75a in _start ()
```

**Comment by zzag** [comment]
This bug should be fixed in 4.1.2
